# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911119325b0a2f8fc5a72156e759e7335241a4ea6ff2caa0612d0cfb10ffb32aa178593b3e4dd5e1af6b81f266d5a161c8e50448a787735ac24f49eb590794d1

test:
  secret_key_base: dbfc8892c1127747babd1870f79200b7a26c145588f0e66239899e38fdeea293a63703cbdffdf862a8865416bfa6688164364ff4b79146044dd11f14be6428be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
